services:
  nest-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rest_service_app
    environment:
      NODE_ENV: development
      PORT: 4002
      DB_TYPE: postgres
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PORT: ${PG_PORT}
      POSTGRES_HOST: ${PG_HOST}
    networks:
      - rest_service_network
    ports:
      - "4002:4002"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: "postgres"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    networks:
      - rest_service_network
    ports:
      - "5432:5432"
    restart: unless-stopped
networks:
  rest_service_network:
    driver: bridge